# Generated by Django 5.0.1 on 2024-02-05 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WindowEfficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_view', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('insulation_efficiency', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.PositiveIntegerField()),
                ('wall_insulation', models.CharField()),
                ('roof_insulation', models.CharField()),
                ('floor_insulation', models.CharField()),
                ('heating_method', models.CharField()),
                ('sum_price', models.PositiveIntegerField()),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.windowefficiency')),
            ],
        ),
    ]
